### PR TITLE
Add labels option

### LINKED ISSUE #409: Add labels option
Hi, it would be great to have an option to add label(s) to a closing issue. 

I can possibly create a PR but will need some pointers on how to test the changes.

### PR DESCRIPTION
**Pull request by jabranr**
Resolves #409

### CODE REVIEW

**Comment by peter-evans** [comment]
Hi @jabranr 

Thank you for this contribution!

For consistency, I would love if this feature could be implemented in same way that `labels` are handled in [create-pull-request](https://github.com/peter-evans/create-pull-request/blob/main/src/main.ts#L23).

- Use `utils.getInputAsArray()`
- Use the [same wording](https://github.com/peter-evans/create-pull-request/blob/main/action.yml#L57-L58) for the description.

**Comment by peter-evans** [comment]
Let me merge this to a feature branch so I can make some minor adjustments. Then I'll merge it to `main` with your contributions.

**Comment by peter-evans** [comment]
Released as `v2.2.0` / `v2`.

Note that I removed the functionality to remove all labels when no labels are specified because it's not backwards compatible behaviour. There could be users that apply labels to an issue and want to keep them when the issue is closed via this action. The `labels` input currently allows two modes, an empty string means "do nothing," and any content means "replace labels on the issue with the specified content."

Thank you!

**Comment by jabranr** [comment]
@peter-evans Thank you for picking it up and moving it forward. Apologies that I become quite busy so couldn't find time to return to this any sooner.

**Pull request merged**
